name: chat
version: 0.1.0.0
github: "satosystems/chat"
license: BSD3
author: "Satoshi Ogata"
maintainer: "satosystems@gmail.com"
copyright: "(c) 2023 Satoshi Ogata"

extra-source-files:
  - README.md
  - CHANGELOG.md

synopsis: ChatGPT CLI
category: CLI

description: Please see the README on GitHub at <https://github.com/satosystems/chatgpt-cli#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - http-streams
  - io-streams
  - string-conversions

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  chat:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - chat
