resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/21.yaml

packages:
  - .

extra-include-dirs:
  - /opt/homebrew/opt/openssl/include

extra-lib-dirs:
  - /opt/homebrew/opt/openssl/lib
